os: linux
dist: xenial

language: go
go:
    - "1.13"

stages:
  - lint
  - test
jobs:
  fast_finish: true
  include:
    
    # Lint with with .golangci.yml configuration
    - stage: lint
      before_install:
        - >-
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
            sh -s -- -b $(go env GOPATH)/bin v1.21.0 # pinned
      script:
        - golangci-lint run

    - stage: test
      before_install:
        - go version
      script: 
        - go test -v -race ./...

        #- echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io 
        #- docker push ${DOCKER_REPO} 

notifications:
    email: false
