os: linux
dist: xenial
services: docker

language: go
go:
    - "1.13"

env:
  global:
    - IMAGE_REPO="quay.io/${QUAY_USERNAME}/ibm-spectrum-scale-csi-driver"
    - IMAGE_TAG="${TRAVIS_BRANCH}.${TRAVIS_OS_NAME}"
    - IMAGE_FQN="${IMAGE_REPO}:${IMAGE_TAG}"

stages:
  - lint
  - test
  - build

jobs:
  fast_finish: true
  include:
    
    # Lint with with .golangci.yml configuration
    - stage: lint
      before_install:
        - >-
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
            sh -s -- -b $(go env GOPATH)/bin v1.21.0 # pinned
      script:
        - golangci-lint run

    - stage: test
      before_install:
        - go version
      script: 
        - go test -v -race ./...
    
    - stage: build
      before_install:
        - echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io 
      script:
        - docker build -f Dockerfile.msb -t ${IMAGE_FQN} .
        - docker push ${IMAGE_FQN}

notifications:
    email: false
