os: linux
dist: xenial
services: docker

language: go
go:
    - "1.13"

env:
  global:
    - REPO_NAME="$(basename $TRAVIS_REPO_SLUG)"
    - IMAGE_REPO="quay.io/${QUAY_USERNAME}/${REPO_NAME}"
    - IMAGE_TAG="${TRAVIS_BRANCH}.${TRAVIS_CPU_ARCH}"
    - IMAGE_FQN="${IMAGE_REPO}:${IMAGE_TAG}"

stages:
  - lint
  - test
  - build

jobs:
  fast_finish: true
  include:
    
    # Lint with with .golangci.yml configuration
    - stage: lint
      before_install:
        - >-
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
            sh -s -- -b $(go env GOPATH)/bin v1.21.0 # pinned
      script:
        - golangci-lint run

    - stage: test
      script: 
        - go test -v -race ./...
    
    - stage: build
      script:
        - docker build -f Dockerfile.msb -t ${REPO_NAME} .

deploy:
  provider: script
  script:
    - echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
    - docker tag ${REPO_NAME} ${IMAGE_FQN}
    - docker push ${IMAGE_FQN}
  on:
    condition: env(QUAY_USERNAME) IS present

notifications:
    email: false
