os: linux
dist: xenial
services: docker

language: go
go:
  - "1.13"

env:
  global:
    - GOFLAGS="-mod=vendor" #this should not be required in Go 1.14, see https://github.com/golang/go/issues/33848
    - REPO_OWNER="$(if [[ -z $QUAY_USERNAME ]]; then dirname $TRAVIS_REPO_SLUG; else echo $QUAY_USERNAME; fi)"
    - REPO_NAME="$(basename $TRAVIS_REPO_SLUG)"
    - IMAGE_REPO="quay.io/${REPO_OWNER}/${REPO_NAME}"
    - IMAGE_TAG="${TRAVIS_BRANCH}"
    - IMAGE_FQN="${IMAGE_REPO}:${IMAGE_TAG}"

stages:
  - lint
  - test

jobs:
  fast_finish: true
  include:
    # Lint with with .golangci.yml configuration
    - stage: lint
      before_install:
        - >-
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
          sh -s -- -b $(go env GOPATH)/bin v1.21.0 # pinned
      script:
        - golangci-lint run

    - stage: test
      before_script:
        - go mod vendor
      script:
        - go test -v -race ./...
        - docker build --build-arg GOFLAGS=${GOFLAGS} -f Dockerfile.msb -t ${REPO_NAME} .
      before_deploy:
          - echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
          - docker tag ${REPO_NAME} ${IMAGE_FQN}
      deploy:
        provider: script
        script: docker push ${IMAGE_FQN}
        on:
          all_branches: true
          condition: -n "$QUAY_BOT_USERNAME" && -n "$QUAY_BOT_PASSWORD"

notifications:
  email: false
