apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-lt
provisioner: ibm-spectrum-scale-csi
parameters:
    volBackendFs: "gpfs0"
    volDirBasePath: "pvfileset/lwdir"
reclaimPolicy: Delete

