apiVersion: v1
kind: PersistentVolume
metadata:
        name: static-scale-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: ibm-spectrum-scale-csi
    volumeHandle: "clusterID;FSUID;path=/gpfs/fs1/staticdir"

